### ISSUE TITLE
Fill out the side navigation for the app

### ISSUE THREAD

**Issue by ZeldaMazzy** [ZeldaMazzy/sicc#9]
Fill out the HTML, css and typescript logic for the SICC sidebar. Here is what the sidebar currently should look like:

![Image](https://github.com/ZeldaMazzy/sicc/assets/69434725/f6584547-c1d1-4abf-9fcc-33af96ffbdfd)

Here is the logo, transparent, in white:

![Image](https://github.com/ZeldaMazzy/sicc/assets/69434725/5528b439-b880-4dc4-ac91-9ca818288fca)

Here are the color hex codes:

Background - `#121239`
Border - `1px solid #2B2B66`
Active Tab Background - `#060628`
Active Text (logo, login, and "Objectives") - `#EEF2F5`
Inactive Text ("Missions", "My Tasks") - `#C9C9C9`

The sidebar needs the following things:
- The logo at the top 
- A list of destinations with an icon to suit each one (use Google's material icons library)
  - Use `routerLink` to link to the different pages ("missions", "mission-control", "my-tasks", and "settings")
- A logout button at the bottom (this will be implemented later).

**Comment by Slingshot1942** [comment]
Used font awesome library instead of material icons
